name: Linter

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  linter:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}

      - name: gitleaks/gitleaks-action
        uses: gitleaks/gitleaks-action@v2 # v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITLEAKS_CONFIG: ".gitleaks.toml"
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
          # GITLEAKS_NOTIFY_USER_LIST: "@mjdusa"

      - name: Install nilaway
        run: |
          go install go.uber.org/nilaway/cmd/nilaway@latest

      - name: Run nilaway
        run: |
          nilaway ./...
