name: Tests

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}

      - name: actions/setup-go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: |
          go version

      - name: go clean --cache
        run: |
          go clean --cache

      - name: go test -race -coverprofile=coverage.gcov -covermode=atomic ./...
        run: |
          go env
          go test -race -coverprofile=coverage.gcov -covermode=atomic ./...

      - name: jandelgado/gcov2lcov-action
        uses: jandelgado/gcov2lcov-action@c680c0f7c7442485f1749eb2a13e54a686e76eb5  # v1.0.9
        with:
          infile: coverage.gcov
          outfile: coverage.lcov

      - name: VeryGoodOpenSource/very_good_coverage
        uses: VeryGoodOpenSource/very_good_coverage@3b475421464c564c0714d92ce02742bd81fa9eda  # v2.2.0
        with:
          path: coverage.lcov
          min_coverage: 85

      # Upload generated artifacts for historical reference
      - name: actions/upload-artifact
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6  # v4.2.0
        with:
          name: test-reports
          path: ./coverage.*
          retention-days: 90
